-- You don't need to set any of these options.
-- IMPORTANT!: this is only a showcase of how you can set default options!
-- local fb_actions = require "telescope".extensions.file_browser.actions
-- require("telescope").setup {
--   extensions = {
--     file_browser = {
--       theme = "dropdown",
--       cwd_to_path = true,
--       dir_icon = "🗀",
--       hidden = true,
--       hijack_netrw = true,
--       select_buffer = true,
--       mappings = {
--         ["n"] = {
--             ['<C-a>'] = fb_actions.create,
--             ['<C-r>'] = fb_actions.rename,
--             ['<C-d>'] = fb_actions.remove,
--         },
--       },
--     },
--   },
-- }
-- -- To get telescope-file-browser loaded and working with telescope,
-- -- you need to call load_extension, somewhere after setup function:
-- require("telescope").load_extension "file_browser"
